In [125]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import datasets, linear_model
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [91]:
df = pd.read_csv("bank.csv")
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [ ]:
df_onehot = pd.get_dummies(df[["job","marital","education","default","housing","loan","contact","month","poutcome",]])
df_onehot

df_new = df_onehot.join(df[["age", "balance","day","duration","campaign","pdays","previous", "deposit"]])
df_new

y, x = df_new.pop("deposit"), df_new

In [102]:
y = y.replace({"yes":1, "no":0})

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

In [128]:
y_pred = lm.predict(X_test)
y_pred

array([0.32971782, 0.88941056, 0.51078855, ..., 0.30305559, 0.34542946,
       0.47481065])

In [129]:
accuracy_score(y_test, y_pred)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [ ]:
clf = tree.DecisionTreeClassifier(max_depth = 2)
clf.fit(X_train, y_train)
tree.plot_tree(clf)